// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NFL_Today.Models;

#nullable disable

namespace NFL_Today.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230306224750_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("NFL_Today.Models.Teams", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PTS")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FPTS")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Plays")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Yds")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Int")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pass_Yds")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pass_Att")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pass_Comp")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pass_TD")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rush_Yds")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rush_Att")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rush_TD")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int>("TD")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RZ_Att")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RZ_TD")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RZ_TD1")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RZ_2D")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RZ_3D")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RZ_4D")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int>("TO")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SCKS_Allow")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
